[package]
name = "netscan"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.100"
clap = { version = "4.5.51", features = ["derive"] }
futures = "0.3.31"
ipnetwork = "0.21.1"
surge-ping = "0.8"
tokio = {version = "1.48.0", features = ["full"]}
dns-lookup = "2.0"
