[package]
name = "netscan"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.100"
clap = { version = "4.5.51", features = ["derive"] }
ipnetwork = "0.21.1"
ping = "0.6.1"
tokio = {version = "1.48.0", features = ["full"]}
